- hosts: paystub
  name: paystub-sinatra
  gather_facts: yes
  vars:
    paystub_repo: https://github.com/ryanbreed/paystub-sinatra
    paystub_path: /app/ruby/paystub-sinatra
    paystub_user: app-ruby
    paystub_group: app-ruby
    paystub_user_home: /app/ruby/home
    paystub_bundle: /usr/local/bin/bundle
  tasks:
    - name: create base dirs
      file: path={{paystub_path}} state=directory recurse=true 
    - name: install app-ruby user
      user: name="{{paystub_user}}" home="{{paystub_user_home}}" shell="/bin/bash" createhome=True skeleton=/etc/skel uid=8000
    - name: install fedora packages
      dnf: name={{item}} state=installed
      with_items: 
       - gcc
       - libffi
       - libffi-devel
    - name: install packages
      yum: name={{item}} state=installed
      with_items:
       - strace
       - git
       - lsof
       - libffi
       - libffi-devel
      when: ansible_system=="Linux" and ansible_distribution=="Centos"

    - name: install app
      git: repo={{paystub_repo}} dest={{paystub_path}} clone=yes update=yes
    - name: install bundle
      bundler: state=present gem_path=vendor/bundle clean=True chdir={{paystub_path}} executable={{paystub_bundle}}
      when: False
    - name: fixup app directory
      file: path={{item}} owner={{paystub_user}} group={{paystub_group}} state=directory
      with_items:
        - "{{paystub_path}}/tmp"
    - name: authorized keys
      authorized_key: manage_dir=yes key="{{item}}" user={{paystub_user}}
      with_items:
       - ""
       

