- hosts: all
  name: paystub-sinatra
  vars:
    paystub_repo: https://github.com/ryanbreed/paystub-sinatra
    paystub_path: /app/ruby/paystub-sinatra
    paystub_user: app-ruby
    paystub_group: app-ruby
    paystub_user_home: /app/ruby/home
    paystub_ruby:   /app/ruby/2.3.3/bin/ruby
    paystub_bundle: /app/ruby/2.3.3/bin/bundle
  tasks:
    - name: install base audit rules
      copy: src=dist/rules.d/ dest=/etc/audit/rules.d/ owner=root group=root
      notify:
        - reload rules

    - name: configure runtime audit rules
      template: src=templates/50-runtime-ruby.rules.j2 dest=/etc/audit/rules.d/50-runtime-ruby.rules owner=root group=root
      notify:
        - reload rules

    - name: install packages
      yum: name={{item}} state=installed
      with_items:
       - strace
       - git
       - lsof
       - libffi-devel

    - name: install app
      git: repo={{paystub_repo}} dest={{paystub_path}} clone=yes update=yes

    - name: install bundle
      bundler: state=present gem_path=vendor/bundle clean=True chdir={{paystub_path}} executable={{paystub_bundle}}

    - name: fixup app directory
      file: path={{item}} owner={{paystub_user}} group={{paystub_group}} state=directory
      with_items:
        - "{{paystub_path}}/tmp"

  handlers:
    - name: reload rules
      command: augenrules --load
      notify:
        - restart rsyslog
    - name: restart rsyslog
      systemd: service=rsyslog state=restarted
